const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=$('.menu'),nav=$('.nav nav');
const setMenu=open=>{document.body.classList.toggle('menu-open',open);nav?.classList.toggle('open',open);if(menu)menu.setAttribute('aria-expanded',String(open))};
menu?.addEventListener('click',()=>setMenu(!document.body.classList.contains('menu-open')));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
$$('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const code=btn.dataset.code||'';try{await navigator.clipboard.writeText(code)}catch{const ta=document.createElement('textarea');ta.value=code;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const old=btn.textContent;btn.textContent='Copied';setTimeout(()=>btn.textContent=old,1100)}));
const cards=$$('.component'),filters=$$('.filter'),search=$('#search'),empty=$('#empty');
function render(){const active=$('.filter.active')?.dataset.filter||'all',q=(search?.value||'').trim().toLowerCase();let visible=0;$$('.component').forEach(card=>{const okCat=active==='all'||card.dataset.category===active;const name=(card.dataset.name||'').toLowerCase();const show=okCat&&(!q||name.includes(q));card.classList.toggle('hidden',!show);if(show)visible++});if(empty)empty.style.display=visible?'none':'block'}
filters.forEach(f=>f.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));f.classList.add('active');render()}));search?.addEventListener('input',render);
function bindInteractions(root=document){$$( '[data-tilt]',root).forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(700px) rotateX(${-y*12}deg) rotateY(${x*14}deg) translateY(-3px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});$$( '.magnetic',root).forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.22,y=(e.clientY-r.top-r.height/2)*.22;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});$$( '.spotlight-card',root).forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${e.clientX-r.left}px`);el.style.setProperty('--my',`${e.clientY-r.top}px`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--mx','50%');el.style.setProperty('--my','50%')})});$$( '.copy',root).forEach(btn=>btn.addEventListener('click',async()=>{const code=btn.dataset.code||'';try{await navigator.clipboard.writeText(code)}catch{const ta=document.createElement('textarea');ta.value=code;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const old=btn.textContent;btn.textContent='Copied';setTimeout(()=>btn.textContent=old,1100)}))}
const scramble=$('#scramble'),chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let scrambleTimer;function scrambleText(){if(!scramble)return;const target=scramble.dataset.target||scramble.textContent;let frame=0;clearInterval(scrambleTimer);scrambleTimer=setInterval(()=>{scramble.textContent=target.split('').map((c,i)=>c===' '?c:i<frame?c:chars[Math.floor(Math.random()*chars.length)]).join('');if(++frame>target.length)clearInterval(scrambleTimer)},45)}scrambleText();scramble?.addEventListener('mouseenter',scrambleText);

// Extra starter library: 14 reusable demos, bringing the homepage library to 20.
const extra=[
['hover','glow button','Glow Button','Soft hover bloom','<button class="glow-button">Glow</button>','<button class="glow-button">Glow</button>'],
['hover','underline link','Animated Underline','Directional link underline','<a class="animated-link">Explore</a>','<a class="animated-link">Explore</a>'],
['cards','depth card','Depth Card','Layered hover depth','<div class="depth-card">Depth</div>','<div class="depth-card">Depth</div>'],
['cards','flip card','Flip Card','3D front/back reveal','<div class="flip-card"><span>Front</span></div>','<div class="flip-card"><span>Front</span></div>'],
['text','typewriter','Typewriter','Sequential character reveal','<span class="typewriter">Hello, motion.</span>','<span class="typewriter">Hello, motion.</span>'],
['text','gradient text','Gradient Text','Animated gradient lettering','<h2 class="gradient-text">Gradient</h2>','<h2 class="gradient-text">Gradient</h2>'],
['text','letter wave','Letter Wave','Hover-driven letter rhythm','<span class="letter-wave">WAVE</span>','<span class="letter-wave">WAVE</span>'],
['background','grid pulse','Grid Pulse','Breathing perspective grid','<div class="grid-pulse">GRID</div>','<div class="grid-pulse">GRID</div>'],
['background','particles','Particle Field','Lightweight floating particles','<div class="particle-field"></div>','<div class="particle-field"></div>'],
['background','mesh gradient','Mesh Gradient','Slow moving color mesh','<div class="mesh-gradient"></div>','<div class="mesh-gradient"></div>'],
['hover','ripple button','Ripple Button','Click ripple interaction','<button class="ripple-button">Click</button>','<button class="ripple-button">Click</button>'],
['hover','border beam','Border Beam','Animated border highlight','<div class="border-beam">BEAM</div>','<div class="border-beam">BEAM</div>'],
['cards','elastic card','Elastic Card','Spring-like hover scale','<div class="elastic-card">Elastic</div>','<div class="elastic-card">Elastic</div>'],
['text','count up','Count Up','Animated number transition','<span class="count-up">2026</span>','<span class="count-up">2026</span>']
];
const grid=$('#componentGrid');if(grid){extra.forEach(([cat,name,title,desc,html,code],i)=>{const article=document.createElement('article');article.className='component';article.dataset.category=cat;article.dataset.name=name;article.innerHTML=`<div class="demo extra-demo extra-${i}">${html}</div><div class="component-info"><div><h3>${title}</h3><p>${desc}</p></div><button class="copy" data-code='${code.replaceAll("'","&#39;")}'>Copy</button></div>`;grid.appendChild(article)});bindInteractions(grid)}

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.08});$$('.section,.cta,.component,.template').forEach(el=>observer.observe(el));render();
