const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=$('.menu'),nav=$('.nav nav');
const setMenu=open=>{document.body.classList.toggle('menu-open',open);nav?.classList.toggle('open',open);if(menu)menu.setAttribute('aria-expanded',String(open))};
menu?.addEventListener('click',()=>setMenu(!document.body.classList.contains('menu-open')));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
const library=[
['hover','magnetic-button','Magnetic Button','Cursor-reactive movement'],['cards','tilt-card','Tilt Card','Depth-aware 3D interaction'],['text','text-reveal','Text Reveal','Staggered entrance animation'],['hover','spotlight-card','Spotlight Card','Pointer-tracking radial glow'],['background','aurora-background','Aurora Background','Soft animated color field'],['text','scramble-text','Scramble Text','Character morphing effect'],['hover','glow-button','Glow Button','Soft hover bloom'],['hover','animated-underline','Animated Underline','Directional link underline'],['cards','depth-card','Depth Card','Layered hover depth'],['cards','flip-card','Flip Card','3D front/back reveal'],['text','typewriter','Typewriter','Sequential character reveal'],['text','gradient-text','Gradient Text','Animated gradient lettering'],['text','letter-wave','Letter Wave','Hover-driven letter rhythm'],['background','grid-pulse','Grid Pulse','Breathing perspective grid'],['background','particle-field','Particle Field','Floating particle motion'],['background','mesh-gradient','Mesh Gradient','Slow moving color mesh'],['hover','ripple-button','Ripple Button','Click ripple interaction'],['hover','border-beam','Border Beam','Animated border highlight'],['cards','elastic-card','Elastic Card','Spring-like hover scale'],['text','count-up','Count Up','Animated number transition']];
function copyText(code,btn){(async()=>{try{await navigator.clipboard.writeText(code)}catch{const ta=document.createElement('textarea');ta.value=code;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const old=btn.textContent;btn.textContent='Copied';setTimeout(()=>btn.textContent=old,1100)})()}
function bindInteractions(root=document){$$('.magnetic',root).forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.22}px,${(e.clientY-r.top-r.height/2)*.22}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});$$('[data-tilt]',root).forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(700px) rotateX(${-y*12}deg) rotateY(${x*14}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});$$('.spotlight-card',root).forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${e.clientX-r.left}px`);el.style.setProperty('--my',`${e.clientY-r.top}px`)}));$$('.copy',root).forEach(btn=>btn.addEventListener('click',()=>copyText(btn.dataset.code||'',btn)))}
const grid=$('#componentGrid');
if(grid){library.forEach(([cat,slug,title,desc])=>{const a=document.createElement('a');a.className='component component-link';a.dataset.category=cat;a.dataset.name=`${title} ${desc}`.toLowerCase();a.href=`components/${slug}.html`;a.innerHTML=`<div class="demo"><div class="library-preview preview-${slug}"><span>${cat.toUpperCase()}</span><strong>${title}</strong></div></div><div class="component-info"><div><h3>${title}</h3><p>${desc}</p></div><span class="open-arrow">↗</span></div>`;grid.appendChild(a)})}
const cards=$$('.component'),filters=$$('.filter'),search=$('#search'),empty=$('#empty');function render(){const active=$('.filter.active')?.dataset.filter||'all',q=(search?.value||'').trim().toLowerCase();let visible=0;cards.forEach(card=>{const okCat=active==='all'||card.dataset.category===active;const show=okCat&&(!q||(card.dataset.name||'').includes(q));card.classList.toggle('hidden',!show);if(show)visible++});if(empty)empty.style.display=visible?'none':'block')};filters.forEach(f=>f.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));f.classList.add('active');render()}));search?.addEventListener('input',render);bindInteractions();render();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.08});$$('.section,.cta,.component,.template').forEach(el=>observer.observe(el));